name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  deployment_pipeline:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install && cd phonebook && npm install && cd..
      - name: lint
        run: npm run lint
  deployment_pipeline_continues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install && cd phonebook && npm install && cd..    

      - name: build
        run: npm run build:ui
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "whispering-bastion-46292"
          heroku_email: "joonas.vanhalakka@helsinki.fi"

